trigger:
- master

jobs:
- job: pod
  pool:
    vmImage: 'macos-latest'
  steps:
  - bash: ./pod.sh
- job: Xcode10_2
  pool:
    vmImage: 'macos-latest'
  steps:
  - bash: Tests/test_xcodebuild.sh Xcode_10.2.1
    env:
      IOS_DEVICE: 'platform=iOS Simulator,OS=12.2,name=iPhone SE'
      TVOS_DEVICE: 'platform=tvOS Simulator,OS=12.2,name=Apple TV 4K'
      CODECOV_JOB: 'true'
      CODECOV_TOKEN: $(codecovToken)
- job: SwiftPM
  pool:
    vmImage: 'macos-latest'
  steps:
  - script: Tests/test_xcodebuild.sh
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  container: norionomura/swift:501
  steps:
  - script: ./test_linux.sh
